<a href="https://colab.research.google.com/github/Vani2130/Quantum-computing/blob/main/Final_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Define the W state vector
W_state = (1/np.sqrt(3)) * np.array([0, 1, 1, 0, 1, 0, 0, 0])

# Compute the density matrix as the outer product |W><W|
density_matrix = np.outer(W_state, W_state.conj())

# Display the density matrix
density_matrix


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.33333333, 0.        , 0.33333333,
        0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.33333333, 0.        , 0.33333333,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.33333333, 0.        , 0.33333333,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ]])

In [2]:
import numpy as np

# Define the identity matrix I and the T matrix
I = np.eye(2)
T = np.array([[1, 0], [0, 0]])

# Define the W state vector and its density matrix
W_state = (1/np.sqrt(3)) * np.array([0, 1, 1, 0, 1, 0, 0, 0])
rho_ABC = np.outer(W_state, W_state.conj())

# Compute the Kronecker products
I_I_I = np.kron(np.kron(I, I), I)
T_I_I = np.kron(np.kron(T, I), I)

# Define the coefficients
coef1 = 1/10
coef2 = 1/5

# Compute the new density matrix
new_density_matrix = coef1 * I_I_I + coef2 * (T_I_I @ rho_ABC @ T_I_I.T.conj())

# Display the new density matrix
new_density_matrix


array([[0.1       , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.16666667, 0.06666667, 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.06666667, 0.16666667, 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.1       , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.1       ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.1       , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.1       , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.1       ]])

In [3]:
import numpy as np
from scipy.linalg import eigh

# Define the initial density matrix rho_1 (density matrix of the W state)
W_state = (1/np.sqrt(3)) * np.array([0, 1, 1, 0, 1, 0, 0, 0])
rho_1 = np.outer(W_state, W_state.conj())

# Define the target density matrix rho_2
I = np.eye(2)
T = np.array([[1, 0], [0, 0]])
I_I_I = np.kron(np.kron(I, I), I)
T_I_I = np.kron(np.kron(T, I), I)

coef1 = 1/10
coef2 = 1/5

rho_2 = coef1 * I_I_I + coef2 * (T_I_I @ rho_1 @ T_I_I.T.conj())

# Diagonalize both density matrices
eigvals_1, eigvecs_1 = eigh(rho_1)
eigvals_2, eigvecs_2 = eigh(rho_2)

# Construct the unitary matrix U
U = eigvecs_2 @ eigvecs_1.T.conj()

# Verify the transformation
transformed_rho_1 = U @ rho_1 @ U.T.conj()

# Display the results
print("Eigenvalues of rho_1:")
print(eigvals_1)
print("\nEigenvectors of rho_1:")
print(eigvecs_1)
print("\nEigenvalues of rho_2:")
print(eigvals_2)
print("\nEigenvectors of rho_2:")
print(eigvecs_2)
print("\nUnitary transformation matrix U:")
print(U)
print("\nTransformed rho_1 (should be close to rho_2):")
print(transformed_rho_1)
print("\nTarget density matrix rho_2:")
print(rho_2)


Eigenvalues of rho_1:
[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 2.22044605e-16 1.00000000e+00]

Eigenvectors of rho_1:
[[ 1.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.81649658 -0.57735027]
 [ 0.         -0.70710678  0.          0.          0.          0.
  -0.40824829 -0.57735027]
 [ 0.          0.          1.          0.          0.          0.
   0.          0.        ]
 [ 0.          0.70710678  0.          0.          0.          0.
  -0.40824829 -0.57735027]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          1.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          1.
   0.          0.        ]]

Eigenvalues of rho_2:
[0.1        0.1        0.1        0.1        0.1        0.1
 0.

In [1]:
!pip install qiskit

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 11.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 20.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.4/39.4 MB 11.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.5/107.5 kB 11.2 MB/s eta 0:00:00


In [3]:
from qiskit import QuantumCircuit
from qiskit.circuit.library import UnitaryGate
import numpy as np

# Define the unitary matrix U
U = np.array([
    [1.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
    [0.        , -0.98559856, -0.11957316,  0.        , -0.11957316,  0.        ,  0.        ,  0.        ],
    [0.        ,  0.16910198, -0.69692343,  0.        , -0.69692343,  0.        ,  0.        ,  0.        ],
    [0.        ,  0.        , -0.70710678,  0.        ,  0.70710678,  0.        ,  0.        ,  0.        ],
    [0.        ,  0.        ,  0.        ,  1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
    [0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  1.        ,  0.        ,  0.        ],
    [0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
    [0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  1.        ]
])

# Create a quantum circuit with 3 qubits
qc = QuantumCircuit(3)

# Add the unitary operation as a gate
unitary_gate = UnitaryGate(U)
qc.append(unitary_gate, [0, 1, 2])

# Print the quantum circuit
print(qc)


     ┌──────────┐
q_0: ┤0         ├
     │          │
q_1: ┤1 Unitary ├
     │          │
q_2: ┤2         ├
     └──────────┘


In [4]:
import numpy as np

# Define the given unitary matrix U
U = np.array([
    [1.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
    [0.        , -0.98559856, -0.11957316,  0.        , -0.11957316,  0.        ,  0.        ,  0.        ],
    [0.        ,  0.16910198, -0.69692343,  0.        , -0.69692343,  0.        ,  0.        ,  0.        ],
    [0.        ,  0.        , -0.70710678,  0.        ,  0.70710678,  0.        ,  0.        ,  0.        ],
    [0.        ,  0.        ,  0.        ,  1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
    [0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  1.        ,  0.        ,  0.        ],
    [0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
    [0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  1.        ]
])

# Extract state vectors from the columns of U
nu_1 = U[:, 0]
nu_2 = U[:, 1]
nu_3 = U[:, 2]
nu_4 = U[:, 3]

# Normalize the state vectors
nu_1 /= np.linalg.norm(nu_1)
nu_2 /= np.linalg.norm(nu_2)
nu_3 /= np.linalg.norm(nu_3)
nu_4 /= np.linalg.norm(nu_4)

# Print the normalized state vectors
print("Normalized state vectors:")
print("nu_1:", nu_1)
print("nu_2:", nu_2)
print("nu_3:", nu_3)
print("nu_4:", nu_4)


Normalized state vectors:
nu_1: [1. 0. 0. 0. 0. 0. 0. 0.]
nu_2: [ 0.         -0.98559856  0.16910198  0.          0.          0.
  0.          0.        ]
nu_3: [ 0.         -0.11957316 -0.69692343 -0.70710678  0.          0.
  0.          0.        ]
nu_4: [0. 0. 0. 0. 1. 0. 0. 0.]


In [6]:
# Reconstruct the unitary matrix using the projection operators
U_reconstructed = P_1 + P_2 + P_3 + P_4

# Print the reconstructed unitary matrix
print("Reconstructed unitary matrix:")
print(U_reconstructed)

# Verify that the reconstructed matrix matches the original matrix
print("Original unitary matrix:")
print(U)
print("Difference:")
print(U - U_reconstructed)


Reconstructed unitary matrix:
[[ 1.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.          0.98570226 -0.08333333  0.08455099  0.          0.
   0.          0.        ]
 [ 0.         -0.08333333  0.51429774  0.49279928  0.          0.
   0.          0.        ]
 [ 0.          0.08455099  0.49279928  0.5         0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          1.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.        ]]
Original unitary matrix:
[[ 1.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.         -0.98559856 -0.11957316  0.         -0.11957316  0.
   0.          0.        ]
 [ 0.         

In [5]:
# Compute the projection operators
P_1 = np.outer(nu_1, np.conjugate(nu_1))
P_2 = np.outer(nu_2, np.conjugate(nu_2))
P_3 = np.outer(nu_3, np.conjugate(nu_3))
P_4 = np.outer(nu_4, np.conjugate(nu_4))

# Print the projection operators
print("Projection operators:")
print("P_1:\n", P_1)
print("P_2:\n", P_2)
print("P_3:\n", P_3)
print("P_4:\n", P_4)


Projection operators:
P_1:
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
P_2:
 [[ 0.         -0.          0.          0.          0.          0.
   0.          0.        ]
 [-0.          0.97140452 -0.16666667 -0.         -0.         -0.
  -0.         -0.        ]
 [ 0.         -0.16666667  0.02859548  0.          0.          0.
   0.          0.        ]
 [ 0.         -0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.         -0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.         -0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.         -0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.         -0.          0.          0.          0.          0.
   0.          0.        ]]
P_3: